[package]
name = "wts-translation-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
regex = "1.11.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true