[package]
name = "wts-translation-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
lazy_static = "1.5.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }